##################################
# spring cloud stream binders配置
##################################
spring:
  rabbitmq:
    host: pin.cheelem.com
    port: 5672
    username: admin
    password: pwd
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        websocketMessageIn:
          destination: websocketMessage
          binder: defaultRabbit
        websocketMessageOut:
          destination: websocketMessage
          binder: defaultRabbit
# 这红的估计是IDE自己有问题

#############################
# Eureka 负载均衡配置
#############################
eureka:
  instance:
    appname: Pin-Consumer
    instanceId: Pin-Consumer
    preferIpAddress: true
    ipAddress: 127.0.0.1
  client:
    fetchRegistry: true
    registerWithEureka: true
    enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:5681/eureka

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE
#spring:
#  main:
#    allow-bean-definition-overriding: true