# 使用前请将下列MySQL和Redis设置配置为可用的服务器
# “Pin团” 拼团电商平台
# @author 李林根 李一飞 牛骋 于岱洋 蔡奇峰

server:
  port: 5688

#############################
# Eureka 负载均衡配置
#############################
eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    enabled: true
    serviceUrl:
      defaultZone: http://pin.cheelem.com:5686/eureka

#############################
# MyBatis 配置
#############################
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.neu.shop.pin.model

#############################
# 分页插件配置
#############################
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  helper-dialect: mysql

#############################
# Spring 基本配置
#############################
spring:
  application:
    name: Pin-Provider
  # 远程数据库连接（MySQL）配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hikari 连接池配置
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: PinHikariCP
    password: **YOUR_PASSWORD**
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://**YOUR_SERVER_ADDR**/pin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    username: pin
  # 远程 Redis 配置
  redis:
    database: 8
    # Jedis 连接池配置
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 8000
        min-idle: 0
    password: **YOUR_PASSWORD**
    timeout: 1000
    # Redis 集群配置
    cluster:
      nodes: **YOUR_SERVER_ADDR**:8001,**YOUR_SERVER_ADDR**:8002,**YOUR_SERVER_ADDR2**:8002,**YOUR_SERVER_ADDR2**:8003
      max-redirects: 6
  # 远程 Rabbit MQ 消息队列 配置
  rabbitmq:
    host: pin.cheelem.com
    port: 5672
    username: admin
    password: pwd
  data:
    # Mongo DB 配置
    mongodb:
      uri: mongodb://pin:**YOUR_PASSWORD**@**YOUR_SERVER_ADDR**
      authentication-database: pin
      database: pin
